<?php
require dirname(__DIR__) . '/config.php'; require_login(); update_overdue($pdo);
$page = $_GET['page'] ?? 'dashboard';
$allowed = ['dashboard','books','categories','members','issues','return','overdue','reports','users'];
if (!in_array($page,$allowed,true)) $page='dashboard';

if (is_post()) {
  verify_csrf(); $action=$_POST['action']??'';
  try {
    if ($action==='save_book') {
      $id=(int)($_POST['id']??0); $qty=max(0,(int)$_POST['quantity']);
      if($id){$old=$pdo->prepare('SELECT quantity,available_quantity FROM books WHERE id=?');$old->execute([$id]);$b=$old->fetch();$issued=$b['quantity']-$b['available_quantity'];$avail=max(0,$qty-$issued);$pdo->prepare('UPDATE books SET isbn=?,title=?,author=?,category_id=?,publisher=?,quantity=?,available_quantity=? WHERE id=?')->execute([trim($_POST['isbn']),trim($_POST['title']),trim($_POST['author']),$_POST['category_id']?:null,trim($_POST['publisher']),$qty,$avail,$id]);}
      else{$pdo->prepare('INSERT INTO books(isbn,title,author,category_id,publisher,quantity,available_quantity) VALUES(?,?,?,?,?,?,?)')->execute([trim($_POST['isbn']),trim($_POST['title']),trim($_POST['author']),$_POST['category_id']?:null,trim($_POST['publisher']),$qty,$qty]);} flash('success','Book saved successfully.');
    } elseif($action==='delete_book') {$pdo->prepare('DELETE FROM books WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Book deleted.');}
    elseif($action==='save_category') {$id=(int)($_POST['id']??0);if($id)$pdo->prepare('UPDATE categories SET category_name=?,description=? WHERE id=?')->execute([trim($_POST['category_name']),trim($_POST['description']),$id]);else $pdo->prepare('INSERT INTO categories(category_name,description) VALUES(?,?)')->execute([trim($_POST['category_name']),trim($_POST['description'])]);flash('success','Category saved.');}
    elseif($action==='delete_category') {$pdo->prepare('DELETE FROM categories WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Category deleted.');}
    elseif($action==='save_member') {$id=(int)($_POST['id']??0);$v=[trim($_POST['member_no']),trim($_POST['full_name']),trim($_POST['email']),trim($_POST['phone']),trim($_POST['address'])];if($id){$v[]=$id;$pdo->prepare('UPDATE members SET member_no=?,full_name=?,email=?,phone=?,address=? WHERE id=?')->execute($v);}else $pdo->prepare('INSERT INTO members(member_no,full_name,email,phone,address) VALUES(?,?,?,?,?)')->execute($v);flash('success','Member saved.');}
    elseif($action==='delete_member') {$pdo->prepare('DELETE FROM members WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Member deleted.');}
    elseif($action==='save_user') {
      $id=(int)($_POST['id']??0);$name=trim($_POST['name']??'');$email=trim($_POST['email']??'');$role=$_POST['role']??'member';$status=$_POST['status']??'active';$password=$_POST['password']??'';
      if(!in_array($role,['admin','librarian','member'],true)||!in_array($status,['active','inactive','suspended'],true)||$name===''||!filter_var($email,FILTER_VALIDATE_EMAIL))throw new Exception('Please enter valid user details.');
      if($id){if($password!=='')$pdo->prepare('UPDATE users SET name=?,email=?,role=?,status=?,password=? WHERE id=?')->execute([$name,$email,$role,$status,password_hash($password,PASSWORD_DEFAULT),$id]);else $pdo->prepare('UPDATE users SET name=?,email=?,role=?,status=? WHERE id=?')->execute([$name,$email,$role,$status,$id]);}
      else{if(strlen($password)<6)throw new Exception('Password must contain at least 6 characters.');$pdo->prepare('INSERT INTO users(name,email,password,role,status) VALUES(?,?,?,?,?)')->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT),$role,$status]);}flash('success','User saved successfully.');
    }
    elseif($action==='delete_user') {if((int)$_POST['id']===(int)$_SESSION['user']['id'])throw new Exception('You cannot delete your own account.');$pdo->prepare('DELETE FROM users WHERE id=?')->execute([(int)$_POST['id']]);flash('success','User deleted.');}
    elseif($action==='issue_book') {$pdo->beginTransaction();$book=$pdo->prepare('SELECT available_quantity FROM books WHERE id=? FOR UPDATE');$book->execute([(int)$_POST['book_id']]);if((int)$book->fetchColumn()<1)throw new Exception('Selected book is not available.');$pdo->prepare("INSERT INTO book_issues(member_id,book_id,issue_date,due_date,status) VALUES(?,?,?,?,'issued')")->execute([(int)$_POST['member_id'],(int)$_POST['book_id'],$_POST['issue_date'],$_POST['due_date']]);$pdo->prepare('UPDATE books SET available_quantity=available_quantity-1 WHERE id=?')->execute([(int)$_POST['book_id']]);$pdo->commit();flash('success','Book issued successfully.');}
    elseif($action==='return_book') {$pdo->beginTransaction();$q=$pdo->prepare('SELECT book_id,due_date FROM book_issues WHERE id=? AND return_date IS NULL FOR UPDATE');$q->execute([(int)$_POST['id']]);$issue=$q->fetch();if(!$issue)throw new Exception('Issue record not found.');$days=max(0,(int)((new DateTime($issue['due_date']))->diff(new DateTime())->format('%r%a')));$fine=$days*FINE_PER_DAY;$pdo->prepare("UPDATE book_issues SET return_date=CURDATE(),status='returned',fine=? WHERE id=?")->execute([$fine,(int)$_POST['id']]);$pdo->prepare('UPDATE books SET available_quantity=available_quantity+1 WHERE id=?')->execute([$issue['book_id']]);$pdo->commit();flash('success','Book returned. Fine: Rs. '.number_format($fine,2));}
  } catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error','Could not complete action: '.$e->getMessage());}
  redirect('app.php?page='.urlencode($_POST['return_page']??$page));
}

$titles=['dashboard'=>'Dashboard','books'=>'Book Management','categories'=>'Categories','members'=>'Member Management','issues'=>'Issue Books','return'=>'Return Books','overdue'=>'Overdue Books','reports'=>'Reports','users'=>'User Management'];
$flash=$_SESSION['flash']??null;unset($_SESSION['flash']);
function post_button(string $action,int $id,string $label,string $returnPage,string $class='btn danger'):string{return '<form method="post" class="inline-form" onsubmit="return confirm(\'Are you sure?\')"><input type="hidden" name="csrf" value="'.csrf_token().'"><input type="hidden" name="action" value="'.$action.'"><input type="hidden" name="id" value="'.$id.'"><input type="hidden" name="return_page" value="'.$returnPage.'"><button class="'.$class.'">'.$label.'</button></form>';}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($titles[$page])?> | Library Management System</title><link rel="icon" type="image/svg+xml" href="favicon.ico"><link rel="stylesheet" href="css/admin.css"><link rel="stylesheet" href="css/professional.css"></head><body>
<aside class="sidebar"><a href="app.php" class="side-brand"><span class="brand-mark">📚</span><span><strong>Library</strong><small>Management System</small></span></a><nav>
<?php foreach(['dashboard'=>['⌂','Dashboard'],'books'=>['▤','Book Management'],'categories'=>['▦','Categories'],'members'=>['♙','Member Management'],'issues'=>['↗','Issue Books'],'return'=>['↙','Return Books'],'overdue'=>['!','Overdue Books'],'reports'=>['▥','Reports'],'users'=>['⚙','User Management']] as $key=>$nav):?><a class="<?=$page===$key?'active':''?>" href="app.php?page=<?=$key?>"><span><?=$nav[0]?></span><?=$nav[1]?></a><?php endforeach;?></nav><div class="side-user"><div class="avatar"><?=strtoupper(substr($_SESSION['user']['name'],0,1))?></div><div><strong><?=e($_SESSION['user']['name'])?></strong><small><?=e($_SESSION['user']['role'])?></small></div><a class="logout-link" href="logout.php" title="Logout"><span>↪</span> Logout</a></div></aside>
<main class="content"><header class="topbar"><button class="menu-btn" onclick="document.body.classList.toggle('menu-open')">☰</button><div><p>Library Management</p><h1><?=e($titles[$page])?></h1></div><div class="today"><?=date('D, d M Y')?></div></header>
<?php if($flash):?><div class="alert <?=e($flash['type'])?>"><?=e($flash['message'])?></div><?php endif;?>

<?php if($page==='dashboard'):
$stats=['Total Books'=>$pdo->query('SELECT COALESCE(SUM(quantity),0) FROM books')->fetchColumn(),'Available Books'=>$pdo->query('SELECT COALESCE(SUM(available_quantity),0) FROM books')->fetchColumn(),'Issued Books'=>$pdo->query("SELECT COUNT(*) FROM book_issues WHERE return_date IS NULL")->fetchColumn(),'Members'=>$pdo->query('SELECT COUNT(*) FROM members')->fetchColumn()];
$recent=$pdo->query('SELECT bi.*,m.full_name,b.title FROM book_issues bi JOIN members m ON m.id=bi.member_id JOIN books b ON b.id=bi.book_id ORDER BY bi.id DESC LIMIT 6')->fetchAll(); ?>
<section class="stats"><?php foreach($stats as $label=>$value):?><article><span><?=e($label)?></span><strong><?=e((string)$value)?></strong><small>Current library total</small></article><?php endforeach;?></section>
<section class="panel"><div class="panel-head"><div><h2>Recent activity</h2><p>Latest issued and returned books</p></div><a class="btn" href="app.php?page=issues">Issue a book</a></div><?php table_issues($recent);?></section>

<?php elseif($page==='books'): $search=trim($_GET['q']??'');$stmt=$pdo->prepare('SELECT b.*,c.category_name FROM books b LEFT JOIN categories c ON c.id=b.category_id WHERE b.title LIKE ? OR b.author LIKE ? OR b.isbn LIKE ? ORDER BY b.id DESC');$like="%$search%";$stmt->execute([$like,$like,$like]);$rows=$stmt->fetchAll();$cats=$pdo->query('SELECT * FROM categories ORDER BY category_name')->fetchAll();$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM books WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}?>
<section class="panel form-panel-admin"><h2><?=$edit?'Edit':'Add'?> book</h2><form method="post" class="data-form"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="save_book"><input type="hidden" name="return_page" value="books"><input type="hidden" name="id" value="<?=e((string)($edit['id']??''))?>"><label>ISBN<input name="isbn" value="<?=e($edit['isbn']??'')?>" required></label><label>Title<input name="title" value="<?=e($edit['title']??'')?>" required></label><label>Author<input name="author" value="<?=e($edit['author']??'')?>" required></label><label>Category<select name="category_id"><option value="">Uncategorized</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>" <?=($edit['category_id']??'')==$c['id']?'selected':''?>><?=e($c['category_name'])?></option><?php endforeach;?></select></label><label>Publisher<input name="publisher" value="<?=e($edit['publisher']??'')?>"></label><label>Quantity<input type="number" name="quantity" min="0" value="<?=e((string)($edit['quantity']??1))?>" required></label><button class="btn primary">Save book</button></form></section>
<section class="panel"><div class="panel-head"><h2>All books</h2><form class="search"><input type="hidden" name="page" value="books"><input name="q" value="<?=e($search)?>" placeholder="Search title, author, ISBN"><button class="btn">Search</button></form></div><div class="table-wrap"><table><thead><tr><th>ISBN</th><th>Title</th><th>Author</th><th>Category</th><th>Stock</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['isbn'])?></td><td><strong><?=e($r['title'])?></strong></td><td><?=e($r['author'])?></td><td><?=e($r['category_name']??'—')?></td><td><span class="badge <?=$r['available_quantity']?'green':'red'?>"><?=$r['available_quantity']?> / <?=$r['quantity']?></span></td><td><a class="btn small" href="app.php?page=books&edit=<?=$r['id']?>">Edit</a><?=post_button('delete_book',(int)$r['id'],'Delete','books')?></td></tr><?php endforeach;?></tbody></table></div></section>

<?php elseif($page==='categories'): $rows=$pdo->query('SELECT c.*,COUNT(b.id) book_count FROM categories c LEFT JOIN books b ON b.category_id=c.id GROUP BY c.id ORDER BY c.category_name')->fetchAll();$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM categories WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}?>
<section class="split"><div class="panel"><h2><?=$edit?'Edit':'Add'?> category</h2><form method="post" class="stack-form"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="save_category"><input type="hidden" name="return_page" value="categories"><input type="hidden" name="id" value="<?=e((string)($edit['id']??''))?>"><label>Category name<input name="category_name" value="<?=e($edit['category_name']??'')?>" required></label><label>Description<textarea name="description"><?=e($edit['description']??'')?></textarea></label><button class="btn primary">Save category</button></form></div><div class="panel"><h2>Categories</h2><div class="table-wrap"><table><thead><tr><th>Name</th><th>Books</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['category_name'])?></td><td><?=$r['book_count']?></td><td><a class="btn small" href="app.php?page=categories&edit=<?=$r['id']?>">Edit</a><?=post_button('delete_category',(int)$r['id'],'Delete','categories')?></td></tr><?php endforeach;?></tbody></table></div></div></section>

<?php elseif($page==='members'): $search=trim($_GET['q']??'');$s=$pdo->prepare('SELECT * FROM members WHERE full_name LIKE ? OR member_no LIKE ? OR email LIKE ? ORDER BY id DESC');$like="%$search%";$s->execute([$like,$like,$like]);$rows=$s->fetchAll();$edit=null;if(isset($_GET['edit'])){$x=$pdo->prepare('SELECT * FROM members WHERE id=?');$x->execute([(int)$_GET['edit']]);$edit=$x->fetch();}?>
<section class="panel form-panel-admin"><h2><?=$edit?'Edit':'Add'?> member</h2><form method="post" class="data-form"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="save_member"><input type="hidden" name="return_page" value="members"><input type="hidden" name="id" value="<?=e((string)($edit['id']??''))?>"><label>Member No<input name="member_no" value="<?=e($edit['member_no']??('MEM-'.date('ymd').rand(10,99)))?>" required></label><label>Full name<input name="full_name" value="<?=e($edit['full_name']??'')?>" required></label><label>Email<input type="email" name="email" value="<?=e($edit['email']??'')?>" required></label><label>Phone<input name="phone" value="<?=e($edit['phone']??'')?>"></label><label class="wide">Address<input name="address" value="<?=e($edit['address']??'')?>"></label><button class="btn primary">Save member</button></form></section><section class="panel"><div class="panel-head"><h2>All members</h2><form class="search"><input type="hidden" name="page" value="members"><input name="q" value="<?=e($search)?>" placeholder="Search members"><button class="btn">Search</button></form></div><div class="table-wrap"><table><thead><tr><th>Member No</th><th>Name</th><th>Email</th><th>Phone</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><span class="badge"><?=e($r['member_no'])?></span></td><td><strong><?=e($r['full_name'])?></strong></td><td><?=e($r['email'])?></td><td><?=e($r['phone'])?></td><td><a class="btn small" href="app.php?page=members&edit=<?=$r['id']?>">Edit</a><?=post_button('delete_member',(int)$r['id'],'Delete','members')?></td></tr><?php endforeach;?></tbody></table></div></section>

<?php elseif($page==='issues'): $members=$pdo->query('SELECT * FROM members ORDER BY full_name')->fetchAll();$books=$pdo->query('SELECT * FROM books WHERE available_quantity>0 ORDER BY title')->fetchAll();$rows=$pdo->query("SELECT bi.*,m.full_name,b.title FROM book_issues bi JOIN members m ON m.id=bi.member_id JOIN books b ON b.id=bi.book_id WHERE bi.return_date IS NULL ORDER BY bi.id DESC")->fetchAll();?>
<section class="panel"><h2>Issue a book</h2><form method="post" class="data-form"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="issue_book"><input type="hidden" name="return_page" value="issues"><label>Member<select name="member_id" required><option value="">Select member</option><?php foreach($members as $m):?><option value="<?=$m['id']?>"><?=e($m['member_no'].' — '.$m['full_name'])?></option><?php endforeach;?></select></label><label>Available book<select name="book_id" required><option value="">Select book</option><?php foreach($books as $b):?><option value="<?=$b['id']?>"><?=e($b['title'].' ('.$b['available_quantity'].' available)')?></option><?php endforeach;?></select></label><label>Issue date<input type="date" name="issue_date" value="<?=date('Y-m-d')?>" required></label><label>Due date<input type="date" name="due_date" value="<?=date('Y-m-d',strtotime('+14 days'))?>" min="<?=date('Y-m-d')?>" required></label><button class="btn primary">Issue book</button></form></section><section class="panel"><h2>Currently issued</h2><?php table_issues($rows);?></section>

<?php elseif($page==='return'): $rows=$pdo->query("SELECT bi.*,m.full_name,b.title FROM book_issues bi JOIN members m ON m.id=bi.member_id JOIN books b ON b.id=bi.book_id WHERE bi.return_date IS NULL ORDER BY bi.due_date")->fetchAll();?>
<section class="panel"><div class="panel-head"><div><h2>Books awaiting return</h2><p>Fine rate: Rs. <?=number_format(FINE_PER_DAY,2)?> per overdue day</p></div></div><div class="table-wrap"><table><thead><tr><th>Member</th><th>Book</th><th>Issued</th><th>Due</th><th>Status</th><th>Current fine</th><th>Action</th></tr></thead><tbody><?php foreach($rows as $r):$fine=$r['due_date']<date('Y-m-d')?max(0,(strtotime(date('Y-m-d'))-strtotime($r['due_date']))/86400)*FINE_PER_DAY:0;?><tr><td><?=e($r['full_name'])?></td><td><?=e($r['title'])?></td><td><?=$r['issue_date']?></td><td><?=$r['due_date']?></td><td><span class="badge <?=$r['status']==='overdue'?'red':'amber'?>"><?=$r['status']?></span></td><td>Rs. <?=number_format($fine,2)?></td><td><?=post_button('return_book',(int)$r['id'],'Return','return','btn primary small')?></td></tr><?php endforeach;?></tbody></table></div></section>

<?php elseif($page==='overdue'): $rows=$pdo->query("SELECT bi.*,m.full_name,m.member_no,b.title FROM book_issues bi JOIN members m ON m.id=bi.member_id JOIN books b ON b.id=bi.book_id WHERE bi.status='overdue' AND bi.return_date IS NULL ORDER BY bi.due_date")->fetchAll();?><section class="panel"><h2>Overdue books</h2><?php table_issues($rows);?></section>

<?php elseif($page==='reports'): $filter=$_GET['filter']??'all';$where=$filter==='issued'?"WHERE bi.return_date IS NULL":($filter==='returned'?"WHERE bi.status='returned'":($filter==='overdue'?"WHERE bi.status='overdue'":''));$rows=$pdo->query("SELECT bi.*,m.full_name,m.member_no,b.title FROM book_issues bi JOIN members m ON m.id=bi.member_id JOIN books b ON b.id=bi.book_id $where ORDER BY bi.id DESC")->fetchAll();?><section class="panel"><div class="panel-head"><h2>Library reports</h2><div class="filters"><?php foreach(['all'=>'All','issued'=>'Issued','returned'=>'Returned','overdue'=>'Overdue'] as $k=>$v):?><a class="btn <?=$filter===$k?'primary':''?>" href="app.php?page=reports&filter=<?=$k?>"><?=$v?></a><?php endforeach;?></div></div><?php table_issues($rows);?></section>
<?php elseif($page==='users'): $rows=$pdo->query('SELECT id,name,email,role,status,created_at FROM users ORDER BY id DESC')->fetchAll();$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT id,name,email,role,status FROM users WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}?>
<section class="panel form-panel-admin"><div class="panel-head"><div><h2><?=$edit?'Edit':'Add new'?> user</h2><p>Manage system access and account permissions.</p></div></div><form method="post" class="data-form"><input type="hidden" name="csrf" value="<?=csrf_token()?>"><input type="hidden" name="action" value="save_user"><input type="hidden" name="return_page" value="users"><input type="hidden" name="id" value="<?=e((string)($edit['id']??''))?>"><label>Full name<input name="name" value="<?=e($edit['name']??'')?>" required></label><label>Email address<input type="email" name="email" value="<?=e($edit['email']??'')?>" required></label><label>Password<input type="password" name="password" minlength="6" <?=$edit?'':'required'?> placeholder="<?=$edit?'Leave blank to keep current':'Minimum 6 characters'?>"></label><label>Role<select name="role"><?php foreach(['admin'=>'Administrator','librarian'=>'Librarian','member'=>'Member'] as $k=>$v):?><option value="<?=$k?>" <?=($edit['role']??'member')===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select></label><label>Status<select name="status"><?php foreach(['active','inactive','suspended'] as $v):?><option value="<?=$v?>" <?=($edit['status']??'active')===$v?'selected':''?>><?=ucfirst($v)?></option><?php endforeach;?></select></label><button class="btn primary">Save user</button></form></section>
<section class="panel"><div class="panel-head"><div><h2>System users</h2><p><?=count($rows)?> registered account<?=count($rows)===1?'':'s'?></p></div></div><div class="table-wrap"><table><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th><th>Joined</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><div class="user-cell"><span class="table-avatar"><?=strtoupper(substr($r['name'],0,1))?></span><strong><?=e($r['name'])?></strong></div></td><td><?=e($r['email'])?></td><td><span class="badge"><?=e($r['role'])?></span></td><td><span class="badge <?=$r['status']==='active'?'green':($r['status']==='suspended'?'red':'amber')?>"><?=e($r['status'])?></span></td><td><?=date('d M Y',strtotime($r['created_at']))?></td><td><a class="btn small" href="app.php?page=users&edit=<?=$r['id']?>">Edit</a><?php if((int)$r['id']!==(int)$_SESSION['user']['id']):?><?=post_button('delete_user',(int)$r['id'],'Delete','users')?><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php endif;?>
</main><script>document.querySelectorAll('.alert').forEach(x=>setTimeout(()=>x.remove(),4000));</script></body></html>
<?php function table_issues(array $rows):void{?><div class="table-wrap"><table><thead><tr><th>Member</th><th>Book</th><th>Issue date</th><th>Due date</th><th>Return date</th><th>Status</th><th>Fine</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="7" class="empty">No records found.</td></tr><?php endif;foreach($rows as $r):?><tr><td><?=e($r['full_name'])?></td><td><strong><?=e($r['title'])?></strong></td><td><?=$r['issue_date']?></td><td><?=$r['due_date']?></td><td><?=$r['return_date']?:'—'?></td><td><span class="badge <?=$r['status']==='returned'?'green':($r['status']==='overdue'?'red':'amber')?>"><?=e($r['status'])?></span></td><td>Rs. <?=number_format((float)$r['fine'],2)?></td></tr><?php endforeach;?></tbody></table></div><?php }
